pip_install_packages:
  - name: docker

chat_image: zyabridos/chat:latest
chat_port: 3000

# Datadog
datadog_api_key: "{{ datadog_api_key }}"

datadog_config:
  tags:
    - env:production
    - role:web
  log_enabled: true
  apm_config:
    enabled: true

datadog_checks:
  http_check:
    init_config: {}
    instances:
      - name: datadog_health_check
        url: "https://ansible-container-orchestrator.online/"
        timeout: 5
        method: GET
        http_response_status_code: 200

datadog_manage_config: false
datadog_disable_untracked_checks: true