- name: Install Docker and Pip packages
  hosts: webservers
  become: true
  roles:
    - geerlingguy.docker
    - geerlingguy.pip

- name: Install Chat on Server
  hosts: all
  become: true

  roles:
    - role: geerlingguy.pip
      tags: setup
    - role: geerlingguy.docker
      tags: setup

  tasks:
    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
      become: true
      
    - name: Remove existing Chat container
      community.docker.docker_container:
        name: zyabridos/chat
        state: absent
      failed_when: false
      tags: deploy

    - name: Deploy Chat container
      community.docker.docker_container:
        name: chat
        image: "{{ chat_image }}"
        restart_policy: always
        ports:
          - "{{ chat_port }}:3000"
      tags: deploy
